/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime=false cloudflare-env.d.ts` (hash: 5cd6eeac6f8e5bc1b560babd7b8ce9ad)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		CursorBakuBucket: R2Bucket;
		CursorBakuDB: D1Database;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
